name: spring CD
on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Update submodule
        run: |
          git submodule update --remote

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - name: Make application-prod.yml
#        run: |
#          cd ./src/main/resources
#          touch ./application.yml
#          touch ./application-datasource.yml
#          touch ./application-prod.yml
#
#          echo "$APPLICATION" > ./application.yml
#          echo "$APPLICATION_DATASOURCE" > ./application-datasource.yml
#          echo "$APPLICATION_PROD" > ./application-prod.yml
#        env:
#          APPLICATION: ${{ secrets.APPLICATION }}
#          APPLICATION_DATASOURCE: ${{ secrets.APPLICATION_DATASOURCE }}
#          APPLICATION_PROD: ${{ secrets.APPLICATION_PROD }}
#        shell: bash

      - name: ./gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: Build with Gradle (Test 제외)
        run: ./gradlew build -x test

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Make zip file
        run: |
          mkdir deploy
          cp ./docker/docker-compose.blue.yml ./deploy/
          cp ./docker/docker-compose.green.yml ./deploy/
          cp ./appspec.yml ./deploy/
          cp ./docker/Dockerfile ./deploy/
          cp ./scripts/deploy.sh ./deploy/
          cp ./build/libs/*.jar ./deploy/
          
          echo "${{secrets.DISCORD_SCRIPT}}"> deploy/discord.sh
          zip -r -qq -j ./spring-build.zip ./deploy

      # S3에 zip 파일 업로드
      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./spring-build.zip s3://sku-bucket

      # CodeDeploy에 배포 요청
      - name: Code Deploy Deployment Request
        run: |
          aws deploy create-deployment --application-name sku-codeDeploy \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name sku-codeDeploy-Group \
            --s3-location bucket=sku-bucket,bundleType=zip,key=spring-build.zip

      # discord 알림봇 설정
      - name: Discord Notify
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: "deploy"
          description: "Deploy script 정상적으로 실행 완료"
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
